apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flatgit.fullname" . }}-webhook
  labels:
    {{- include "flatgit.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.webhook.secret | quote }}